security:
    encoders:
        Knax\TestingBundle\Entity\Login:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    providers:
        main:
            entity:
                class: Knax\TestingBundle\Entity\Login
                property: username
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: knax_index
            logout:
                path:   /logout
                target: /
    access_control:
           - { path: ^/secure_area, roles: ROLE_USER }