parameters:
#    knax_testing.example.class: Knax\TestingBundle\Example

services:
#    knax_testing.example:
#        class: %knax_testing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
