<?php

namespace Knax\TestingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AbsentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsentRepository extends EntityRepository
{
    public function getListAbsent($userID)
    {
        $em = $this->getEntityManager();
        $absentList = $em
                    ->createQuery("
                        SELECT a.type
                        FROM KnaxTestingBundle:Absent a
                        WHERE a.userdata = :id
                        ")
                    ->setParameter("id",$userID)
                    ->getResult();
        return $absentList;
    }
}