<?php
namespace Knax\TestingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
    public function getUserMark($studentID)
    {
        $em = $this->getEntityManager();
        $nameList = $em
                    ->createQuery("
                        SELECT u.fullName, m.score, u2.fullName AS teacherName, st.name
                        FROM KnaxTestingBundle:Userdata u
                        JOIN KnaxTestingBundle:Student s WHERE u.id = s.userdata
                        JOIN KnaxTestingBundle:Mark m WHERE m.student = s.userdata
                        JOIN KnaxTestingBundle:Teacher t WHERE m.teacher = t.userdata
                        JOIN KnaxTestingBundle:Userdata u2 WHERE t.userdata = u2.id
                        JOIN KnaxTestingBundle:Studies st WHERE t.studies = st.id
                        WHERE u.id = :id
                        ")
                    ->setParameter("id",$studentID)
                    ->getSingleResult();
        return $nameList;
    }
}
