<?php

namespace Knax\TestingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudiesRepository extends EntityRepository
{
}
